# Generated by Django 2.2.1 on 2021-03-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210310_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_logo',
            new_name='movie_url',
        ),
    ]
