# Generated by Django 2.2.1 on 2021-03-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210310_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_upload', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='Movie/bulkupload')),
            ],
        ),
    ]
