# Generated by Django 2.2.1 on 2021-03-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_moviebulkupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
